groups:
  - name: requisicoes
    rules:
      - alert: taxaDeErros
        expr: rate(http_server_requests_seconds_count{status="500|400"}[10m]) > 0.7
        for: 10m
        labels:
          app: cineminha
          severity: critical
        annotations:
          title: Quantidade de erros do http
          summary: Quantidade de erros 400 e 500 nas requisicoes http
          description: Quantidade de erros que ultrapassaram 70 por cento.
